-- Insert puzzles
insert into public.puzzles (type, sequence_order, title, description, solution_data) values
('symbol_cipher', 1, 'El Cifrado de los Antiguos', 'Decodifica los símbolos lovecraftianos para revelar la palabra oculta.', '{"solution":"CTHULHU","symbols":["☿","⚡","☠","⚜","⬟","☠","⚜"]}'),
('ritual_pattern', 2, 'El Ritual Prohibido', 'Ordena los items rituales en la secuencia correcta para completar el ritual.', '{"solution":["candle","tome","dagger","chalice","skull"],"items":["candle","tome","dagger","chalice","skull"]}'),
('ancient_lock', 3, 'La Cerradura Ancestral', 'Resuelve la combinación basándote en las pistas del entorno.', '{"solution":"7394","clues":["Los tentáculos del horror","Los ángulos de la locura","Los ojos del abismo","Las estrellas alineadas"]}'),
('memory_fragments', 4, 'Fragmentos de Memoria', 'Empareja las imágenes eldritchas antes de que la locura te consuma.', '{"pairs":8,"time_limit":120,"images":["tentacle","eye","star","tome","portal","cultist","monster","rune"]}'),
('cosmic_alignment', 5, 'Alineación Cósmica', 'Alinea los cuerpos celestes para que coincidan con la carta estelar antigua.', '{"solution":["aldebaran","betelgeuse","rigel","sirius","vega"],"positions":[{"x":120,"y":80},{"x":200,"y":150},{"x":300,"y":100},{"x":180,"y":220},{"x":280,"y":180}]}'),
('tentacle_maze', 6, 'El Laberinto de Tentáculos', 'Navega a través del laberinto cambiante evitando los tentáculos.', '{"maze_size":10,"tentacles":5,"exit":{"x":9,"y":9},"start":{"x":0,"y":0}}'),
('forbidden_tome', 7, 'El Tomo Prohibido', 'Reconstruye las páginas desgarradas del libro antiguo en el orden correcto.', '{"solution":[3,1,4,2,5],"pages":["En el principio, los Antiguos...","Desde más allá de las estrellas...","El ritual debe completarse cuando...","Los sellos que los mantienen...","Y así, el mundo conocerá..."]}'),
('shadow_reflection', 8, 'Reflejo de Sombras', 'Refleja los movimientos para que coincidan con los patrones de sombras en la pared.', '{"solution":["up","right","down","left","up","up","right"],"pattern_count":7}'),
('elder_sign', 9, 'El Signo de los Antiguos', 'Traza el patrón geométrico complejo sin levantar el cursor.', '{"points":[{"x":200,"y":100},{"x":300,"y":200},{"x":200,"y":300},{"x":100,"y":200},{"x":200,"y":100}],"tolerance":20,"max_time":60}'),
('cultist_code', 10, 'El Código del Culto - La Prueba Final', 'Decodifica el mensaje final del Necronomicón. Esta es tu última prueba antes de escapar.', '{"solution":"NECRONOMICON","encrypted":"QHFURQRPLFRQ","cipher_type":"caesar","shift":3}');

-- Insert hints
insert into public.hints (puzzle_id, level, content) values
(1, 1, 'Cada símbolo representa una letra. Busca patrones repetidos.'),
(1, 2, 'El primer símbolo es "C". Intenta descifrar el resto.'),
(1, 3, 'La palabra es el nombre del Gran Antiguo que duerme en R''lyeh.'),
(2, 1, 'El ritual comienza con luz y termina con muerte.'),
(2, 2, 'La vela va primero, el cráneo va último.'),
(2, 3, 'Orden: Vela, Tomo, Daga, Cáliz, Cráneo.'),
(3, 1, 'Cuenta los elementos mencionados en cada pista.'),
(3, 2, 'Tentáculos: 7, Ángulos: 3, Ojos: 9, Estrellas: 4.'),
(3, 3, 'La combinación es: 7394.'),
(4, 1, 'Memoriza las posiciones antes de que se volteen.'),
(4, 2, 'Empieza por las esquinas, son más fáciles de recordar.'),
(4, 3, 'Hay 8 pares. Concéntrate en un área a la vez.'),
(5, 1, 'Las estrellas deben formar la constelación correcta.'),
(5, 2, 'Aldebaran va en la parte superior izquierda.'),
(5, 3, 'Sigue el patrón de la carta estelar en el fondo.'),
(6, 1, 'Los tentáculos se mueven en patrones predecibles.'),
(6, 2, 'Espera a que los tentáculos se retiren antes de avanzar.'),
(6, 3, 'El camino más seguro es por el borde derecho.'),
(7, 1, 'Lee el contenido de cada página para encontrar el orden cronológico.'),
(7, 2, 'La página 3 va primero, habla del principio.'),
(7, 3, 'Orden correcto: 3, 1, 4, 2, 5.'),
(8, 1, 'Observa el patrón de sombras cuidadosamente.'),
(8, 2, 'El patrón comienza hacia arriba y termina a la derecha.'),
(8, 3, 'Secuencia: Arriba, Derecha, Abajo, Izquierda, Arriba, Arriba, Derecha.'),
(9, 1, 'Debes trazar el patrón sin levantar el cursor.'),
(9, 2, 'Comienza desde el punto superior y sigue las líneas.'),
(9, 3, 'Forma una estrella de cinco puntas, comenzando arriba.'),
(10, 1, 'Es un cifrado César. Cada letra está desplazada.'),
(10, 2, 'El desplazamiento es de 3 posiciones hacia atrás.'),
(10, 3, 'La palabra es el nombre del libro maldito: NECRONOMICON. Esta es tu prueba final.');
